"""SKLegal provider-neutral model gateway.

Routes approved typed activities to local Qwen or OpenAI through pinned
routes without provider-specific domain coupling. Provider output is always
an immutable Proposal and can never mutate workflow or domain state.
"""

from .admission import AdmissionController
from .audit_records import (
    AUDIT_RECORD_SCHEMA,
    AuditRecord,
    AuditRecorder,
    FailingAuditRecorder,
    InMemoryAuditRecorder,
)
from .capacity import (
    DEFAULT_QWEN_CAPACITY_DOMAIN_ID,
    DEFAULT_QWEN_ENVELOPE,
    CapacityDomainController,
    CapacityEnvelope,
)
from .catalog import (
    CATALOG_SCHEMA,
    CatalogFile,
    FreeRouteRecord,
    ModelCatalog,
    ResolvedTarget,
    ServedModel,
)
from .egress import EgressDecision, EgressGate, PolicyFileEgressGate
from .errors import (
    AuditUnavailableError,
    BucketPolicyError,
    CapabilityDeniedError,
    CapacityDomainNotFoundError,
    CapacityQueueTimeoutError,
    CatalogLookupError,
    ContextBudgetExceededError,
    EgressDeniedError,
    FreeRouteDeniedError,
    ModelCancelledError,
    ModelGatewayError,
    ModelTimeoutError,
    PolicyUnavailableError,
    PromptRenderError,
    ProviderContractError,
    ProviderSaturationError,
    ProviderUnavailableError,
    RetryBudgetExceededError,
    RouteDisabledError,
    RouteIntegrityError,
    RouteNotFoundError,
    SchemaValidationError,
    SecretResolutionError,
    ServedModelAttributionError,
    SourceRightsDeniedError,
    TransportBindingError,
    TransportProfileDisabledError,
    TransportProfileNotFoundError,
    TransportProfileStaleError,
)
from .gateway import CapabilityGate, ModelGateway
from .models import (
    CancellationToken,
    GatewayValue,
    ModelPin,
    ModelRouteRecord,
    PolicyEvidence,
    Proposal,
    ProposalRequest,
    Provider,
    ProviderExecutionContext,
    RedactionRecord,
    ResponseEvidence,
    TokenUsage,
    TransportEvidence,
    TransportKind,
    TransportProfile,
    TrustZone,
    WorkloadClass,
)
from .prompts import FilePromptStore, PromptStore, estimate_tokens, render_prompt
from .providers import (
    ModelProvider,
    OpenAiResponsesProvider,
    OpenAiTransport,
    ProviderCall,
    ProviderResult,
    QwenLocalProvider,
    QwenTransport,
    SecretResolver,
)
from .registry import REGISTRY_SCHEMA, RouteRegistry, sha256_text
from .schemas import (
    CORPUS_SUMMARY_SCHEMA_ID,
    HTWC_PROPOSITIONS_SCHEMA_ID,
    HTWC_WORKFLOW_PACK_SCHEMA_ID,
    CorpusSummaryProposalPayload,
    HTWCPropositionsPayload,
    HTWCWorkflowPackPayload,
    SchemaRegistry,
    schema_sha256,
)
from .skgateway import (
    CONTROL_GATE_REVISION,
    LIVE_PATH_CONTROLS,
    SkGatewayChatProvider,
    SkGatewayChatTransport,
    SkGatewayLivePathGate,
    SkGatewayLivePathReport,
    SkGatewayRouteAuthorizationEvidence,
    SkGatewayRoutePolicyVerifier,
)
from .transport_profiles import (
    PROFILE_STORE_SCHEMA,
    TransportProfileStore,
    profile_content_sha256,
)

__all__ = [
    "AUDIT_RECORD_SCHEMA",
    "CATALOG_SCHEMA",
    "CONTROL_GATE_REVISION",
    "CORPUS_SUMMARY_SCHEMA_ID",
    "HTWC_PROPOSITIONS_SCHEMA_ID",
    "HTWC_WORKFLOW_PACK_SCHEMA_ID",
    "DEFAULT_QWEN_CAPACITY_DOMAIN_ID",
    "DEFAULT_QWEN_ENVELOPE",
    "InMemoryAuditRecorder",
    "LIVE_PATH_CONTROLS",
    "PACKAGE_NAME",
    "PROFILE_STORE_SCHEMA",
    "REGISTRY_SCHEMA",
    "AdmissionController",
    "AuditRecord",
    "AuditRecorder",
    "AuditUnavailableError",
    "Bucket",
    "BucketPolicyError",
    "CapacityDomainController",
    "CapacityDomainNotFoundError",
    "CapacityEnvelope",
    "CapacityQueueTimeoutError",
    "CatalogFile",
    "CatalogLookupError",
    "CancellationToken",
    "CapabilityDeniedError",
    "CapabilityGate",
    "ContextBudgetExceededError",
    "CorpusSummaryProposalPayload",
    "EgressDecision",
    "EgressDeniedError",
    "EgressGate",
    "FailingAuditRecorder",
    "FilePromptStore",
    "FreeRouteDeniedError",
    "FreeRouteRecord",
    "GatewayValue",
    "ModelCancelledError",
    "ModelCatalog",
    "ModelGateway",
    "ModelGatewayError",
    "ModelPin",
    "ModelProvider",
    "ModelRouteRecord",
    "ModelTimeoutError",
    "OpenAiResponsesProvider",
    "OpenAiTransport",
    "PolicyEvidence",
    "PolicyFileEgressGate",
    "PolicyUnavailableError",
    "PromptRenderError",
    "PromptStore",
    "Proposal",
    "ProposalRequest",
    "Provider",
    "ProviderCall",
    "ProviderContractError",
    "ProviderExecutionContext",
    "ProviderResult",
    "ProviderSaturationError",
    "ProviderUnavailableError",
    "QwenLocalProvider",
    "QwenTransport",
    "RedactionRecord",
    "ResolvedTarget",
    "ResponseEvidence",
    "RetryBudgetExceededError",
    "RouteDisabledError",
    "RouteIntegrityError",
    "RouteNotFoundError",
    "RouteRegistry",
    "SchemaRegistry",
    "HTWCPropositionsPayload",
    "HTWCWorkflowPackPayload",
    "SchemaValidationError",
    "SecretResolutionError",
    "SecretResolver",
    "ServedModel",
    "ServedModelAttributionError",
    "SkGatewayChatProvider",
    "SkGatewayChatTransport",
    "SkGatewayLivePathGate",
    "SkGatewayLivePathReport",
    "SkGatewayRouteAuthorizationEvidence",
    "SkGatewayRoutePolicyVerifier",
    "SourceRightsDeniedError",
    "TokenUsage",
    "TransportBindingError",
    "TransportEvidence",
    "TransportKind",
    "TransportProfile",
    "TransportProfileDisabledError",
    "TransportProfileNotFoundError",
    "TransportProfileStaleError",
    "TransportProfileStore",
    "TrustZone",
    "WorkloadClass",
    "estimate_tokens",
    "profile_content_sha256",
    "render_prompt",
    "schema_sha256",
    "sha256_text",
]

PACKAGE_NAME = "sklegal-model-gateway"
