"""Read-only HammerTime release and artifact adapter package.

The adapter is the only SKLegal component allowed to construct HammerTime
paths. It has no write, move, delete, or dispatch surface, never reads
``Inbox/``, and fails closed on matter authorization.
"""

from .adapter import (
    DEFAULT_MAX_ARTIFACT_BYTES,
    ROOT_ENV_VAR,
    HammerTimeReleaseAdapter,
)
from .bridge import (
    HammerTimeSubmissionBridge,
    SourceEntry,
    SubmissionPlan,
    SubmissionResult,
)
from .errors import (
    AdapterUnavailableError,
    AmbiguousLegacyIdError,
    ArtifactTooLargeError,
    CompletionEvidenceMissingError,
    ForbiddenPathError,
    HammerTimeAdapterError,
    MalformedFrontmatterError,
    MalformedManifestError,
    MatterAccessDenied,
    MissingPathError,
    PromotionRejectedError,
    RegistryMismatchError,
    SourceHashMismatchError,
    StaleReleaseError,
    SubmissionError,
    UnsupportedSubmissionError,
)
from .frontmatter import split_frontmatter
from .models import (
    AliasBinding,
    AliasTarget,
    ArtifactRead,
    DecomposedStateSeal,
    Decomposition,
    DecompositionChunk,
    DecompositionClaim,
    DecompositionEntity,
    DecompositionId,
    DocumentCounts,
    LegacyMatterRecord,
    LegacyPathResolution,
    LegacyRecordId,
    MatterAccessRequest,
    MatterArtifact,
    MatterArtifactInventory,
    MatterAuthorizer,
    MatterValidationReport,
    PacketReference,
    RelativePosixPath,
    ReleaseId,
    ReleaseManifest,
    ReleaseSummary,
    ResolvedRelease,
    RuntimeAlias,
    RuntimeAliasesSnapshot,
    SnapshotPin,
    SourceHashVerification,
)
from .release_qualification import (
    AliasRoundTripEvidence,
    OfficialDraftingReleaseQualifier,
    OfficialDraftingReleaseReport,
    OfficialDraftingReleaseRequest,
    OfficialDraftingSource,
    ProjectionQualificationEvidence,
    QualificationFinding,
    QualificationFindingCode,
    QualificationStatus,
    RetrievalHitEvidence,
    ScopedRetrievalEvidence,
    SecondaryReviewEvidence,
    SourceRightsState,
)

PACKAGE_NAME = "sklegal-hammertime"

__all__ = [
    "DEFAULT_MAX_ARTIFACT_BYTES",
    "PACKAGE_NAME",
    "ROOT_ENV_VAR",
    "AdapterUnavailableError",
    "AliasBinding",
    "AliasRoundTripEvidence",
    "AliasTarget",
    "AmbiguousLegacyIdError",
    "ArtifactRead",
    "ArtifactTooLargeError",
    "DecomposedStateSeal",
    "Decomposition",
    "DecompositionClaim",
    "DecompositionChunk",
    "DecompositionEntity",
    "DecompositionId",
    "DocumentCounts",
    "ForbiddenPathError",
    "HammerTimeAdapterError",
    "HammerTimeReleaseAdapter",
    "HammerTimeSubmissionBridge",
    "SourceEntry",
    "SubmissionPlan",
    "SubmissionResult",
    "LegacyMatterRecord",
    "LegacyPathResolution",
    "LegacyRecordId",
    "MalformedFrontmatterError",
    "MalformedManifestError",
    "MatterAccessDenied",
    "MatterAccessRequest",
    "MatterAuthorizer",
    "MatterArtifact",
    "MatterArtifactInventory",
    "MatterValidationReport",
    "MissingPathError",
    "PacketReference",
    "OfficialDraftingReleaseQualifier",
    "OfficialDraftingReleaseReport",
    "OfficialDraftingReleaseRequest",
    "OfficialDraftingSource",
    "ProjectionQualificationEvidence",
    "QualificationFinding",
    "QualificationFindingCode",
    "QualificationStatus",
    "RegistryMismatchError",
    "RelativePosixPath",
    "ReleaseId",
    "ReleaseManifest",
    "ReleaseSummary",
    "RetrievalHitEvidence",
    "ResolvedRelease",
    "RuntimeAlias",
    "RuntimeAliasesSnapshot",
    "SnapshotPin",
    "SourceHashMismatchError",
    "SourceHashVerification",
    "ScopedRetrievalEvidence",
    "SecondaryReviewEvidence",
    "SourceRightsState",
    "StaleReleaseError",
    "CompletionEvidenceMissingError",
    "PromotionRejectedError",
    "SubmissionError",
    "UnsupportedSubmissionError",
    "split_frontmatter",
]
