"""Governed SKLegal retrieval boundary."""

from .contract import (
    CONTRACT_SCHEMA,
    DEFAULT_CONTRACT_PATH,
    EXPECTED_CONTRACT_SHA256,
    ContractValidationError,
    RetrievalContract,
    load_retrieval_contract,
)
from .errors import (
    RetrievalAuthorizationError,
    RetrievalError,
    RetrievalErrorCode,
    RetrievalErrorEnvelope,
    RetrievalIntegrityError,
    RetrievalRequestError,
    RetrievalUnavailableError,
)
from .models import (
    AuthorizationPins,
    BackendAggregateRecord,
    BackendHybridRecord,
    BackendScoredRecord,
    BackendUnavailableComponent,
    CredentialBindingPins,
    DistanceMetric,
    IncompleteComponent,
    IncompleteReason,
    ProjectionPins,
    QueryTemplateId,
    QueryTemplatePins,
    RetrievalAggregateKind,
    RetrievalAggregateValue,
    RetrievalCacheKey,
    RetrievalComponent,
    RetrievalHit,
    RetrievalMode,
    RetrievalProvenance,
    RetrievalRequest,
    RetrievalResult,
    RetrievalScope,
    ScopeKind,
    SourceProvenance,
)
from .orchestrator import (
    ActiveProjectionRegistry,
    CredentialBindingResolver,
    CurrentAuthorizer,
    RetrievalExecutor,
    RetrievalOrchestrator,
)
from .postgres import (
    PostgresBackendResult,
    PostgresQueryRunner,
    PostgresRetrievalAdapter,
)
from .query_templates import (
    BoundQueryTemplate,
    QueryTemplate,
    QueryTemplateError,
    bind_query_template,
    get_query_template,
)

PACKAGE_NAME = "sklegal-retrieval"

__all__ = [
    "CONTRACT_SCHEMA",
    "DEFAULT_CONTRACT_PATH",
    "EXPECTED_CONTRACT_SHA256",
    "PACKAGE_NAME",
    "ActiveProjectionRegistry",
    "AuthorizationPins",
    "BackendAggregateRecord",
    "BackendHybridRecord",
    "BackendScoredRecord",
    "BackendUnavailableComponent",
    "BoundQueryTemplate",
    "ContractValidationError",
    "CredentialBindingPins",
    "CredentialBindingResolver",
    "CurrentAuthorizer",
    "DistanceMetric",
    "IncompleteComponent",
    "IncompleteReason",
    "PostgresBackendResult",
    "PostgresQueryRunner",
    "PostgresRetrievalAdapter",
    "ProjectionPins",
    "QueryTemplate",
    "QueryTemplateError",
    "QueryTemplateId",
    "QueryTemplatePins",
    "RetrievalAggregateKind",
    "RetrievalAggregateValue",
    "RetrievalAuthorizationError",
    "RetrievalCacheKey",
    "RetrievalComponent",
    "RetrievalContract",
    "RetrievalError",
    "RetrievalErrorCode",
    "RetrievalErrorEnvelope",
    "RetrievalExecutor",
    "RetrievalHit",
    "RetrievalIntegrityError",
    "RetrievalMode",
    "RetrievalOrchestrator",
    "RetrievalProvenance",
    "RetrievalRequest",
    "RetrievalRequestError",
    "RetrievalResult",
    "RetrievalScope",
    "RetrievalUnavailableError",
    "ScopeKind",
    "SourceProvenance",
    "bind_query_template",
    "get_query_template",
    "load_retrieval_contract",
]
