"""Database-driver-neutral domain decomposition and strict reconstruction.

Rows must contain native driver values such as ``UUID`` and UTC ``datetime``
objects. Normalized relations are supplied separately and are mandatory when
declared, including when an optional or many-valued relation is empty. This
keeps absent joins distinguishable from intentionally empty domain values.
"""

from .contract import (
    ALIAS_PERSISTENCE,
    AUDIT,
    COMMUNICATION_PARTICIPANT_PERSISTENCE,
    ELEMENT_EVIDENCE_PERSISTENCE,
    EXECUTION_SUBJECT_BINDINGS,
    INTERVAL,
    LINKED_SOURCE_PERSISTENCE,
    PROTECTED,
    REMEDY_AUTHORITY_PERSISTENCE,
    SCOPE_OWNER_BINDINGS,
    SCOPED,
    SOURCE_ONE,
    SOURCE_OPTIONAL,
    SOURCE_ROW_PERSISTENCE,
    SUBJECT,
    TENSION_ASSERTION_PERSISTENCE,
    THEORY_ELEMENT_PERSISTENCE,
    THEORY_LINK_PERSISTENCE,
    TRANSACTION_ROLE_PERSISTENCE,
    VALIDATION_CHECK_PERSISTENCE,
    AuxiliaryWrite,
    CompositeField,
    DecomposedEntity,
    DecompositionWriteContract,
    EntityMapping,
    MappingContractError,
    PersistenceMetadata,
    Reconstruction,
    RelationField,
    RelationMode,
    WriteAuthority,
)
from .decode import (
    ALIAS_COLUMNS,
    SOURCE_COLUMNS,
    reconstruct,
    reconstruct_with_metadata,
)
from .encode import (
    ADMINISTRATIVE_BOOTSTRAP_ENTITIES,
    APPROVAL_OUTPUT_LEAVES,
    CONTROLLED_EVOLUTION_ENTITIES,
    CONTROLLED_WRITER_ENTITIES,
    DATABASE_OUTPUT_LEAVES,
    EXECUTION_EVENT_OUTPUT_LEAVES,
    EXECUTION_RECEIPT_CANONICAL_INPUT_LEAVES,
    EXECUTION_RECEIPT_OUTPUT_LEAVES,
    decompose,
    validate_mapping_contract,
)
from .mappings import MAPPINGS

__all__ = [
    "ADMINISTRATIVE_BOOTSTRAP_ENTITIES",
    "ALIAS_COLUMNS",
    "ALIAS_PERSISTENCE",
    "APPROVAL_OUTPUT_LEAVES",
    "AUDIT",
    "COMMUNICATION_PARTICIPANT_PERSISTENCE",
    "CONTROLLED_EVOLUTION_ENTITIES",
    "CONTROLLED_WRITER_ENTITIES",
    "DATABASE_OUTPUT_LEAVES",
    "ELEMENT_EVIDENCE_PERSISTENCE",
    "EXECUTION_EVENT_OUTPUT_LEAVES",
    "EXECUTION_RECEIPT_CANONICAL_INPUT_LEAVES",
    "EXECUTION_RECEIPT_OUTPUT_LEAVES",
    "EXECUTION_SUBJECT_BINDINGS",
    "INTERVAL",
    "LINKED_SOURCE_PERSISTENCE",
    "MAPPINGS",
    "PROTECTED",
    "REMEDY_AUTHORITY_PERSISTENCE",
    "SCOPED",
    "SCOPE_OWNER_BINDINGS",
    "SOURCE_COLUMNS",
    "SOURCE_ONE",
    "SOURCE_OPTIONAL",
    "SOURCE_ROW_PERSISTENCE",
    "SUBJECT",
    "TENSION_ASSERTION_PERSISTENCE",
    "THEORY_ELEMENT_PERSISTENCE",
    "THEORY_LINK_PERSISTENCE",
    "TRANSACTION_ROLE_PERSISTENCE",
    "VALIDATION_CHECK_PERSISTENCE",
    "AuxiliaryWrite",
    "CompositeField",
    "DecomposedEntity",
    "DecompositionWriteContract",
    "EntityMapping",
    "MappingContractError",
    "PersistenceMetadata",
    "Reconstruction",
    "RelationField",
    "RelationMode",
    "WriteAuthority",
    "decompose",
    "reconstruct",
    "reconstruct_with_metadata",
    "validate_mapping_contract",
]
