"""SKLegal Temporal worker foundations: queues, workflows, activities."""

from .activities import (
    ApprovalGate,
    DispatchLedger,
    FileDispatchLedger,
    InMemoryStaleAlertSink,
    SimulatedDispatchLedger,
    SimulatedStepDriver,
    StaleAlertSink,
    StaticApprovalGate,
    StepDriver,
    WorkerActivities,
)
from .errors import (
    AdmissionRejectedError,
    ApprovalRejectedError,
    ModelUnavailableError,
    PolicyDeniedError,
    WorkflowError,
    WorkflowInvariantError,
)
from .models import (
    TERMINAL_PHASES,
    ApprovalRequirement,
    ApprovalSignal,
    DispatchReceipt,
    DispatchRequest,
    QueueKind,
    RetryClass,
    RunIdentity,
    RunPhase,
    Sha256Digest,
    Slug,
    StaleRunAlert,
    StepActivityInput,
    StepOutcome,
    StepRecord,
    TaskWorkflowInput,
    TaskWorkflowResult,
    UtcDateTime,
    WorkflowPayload,
)
from .queues import (
    INTERACTIVE_CONTEXT_TOKEN_LIMIT,
    LONG_CONTEXT_MAX_CONCURRENT,
    TASK_QUEUE_NAMES,
    AdmissionTicket,
    LongContextAdmission,
    select_queue,
    task_queue_name,
)
from .retry import (
    BASE_NON_RETRYABLE_ERROR_TYPES,
    RETRY_SPECS,
    RetrySpec,
    attempts_exhausted,
    is_retryable,
    retry_policy_for,
    retry_spec_for,
)
from .state import (
    EventKind,
    RunConfig,
    RunEvent,
    WorkflowRunMachine,
)
from .worker import (
    WorkerSpec,
    WORKER_DATA_CONVERTER,
    build_worker,
    connect_worker_client,
    worker_specs,
)
from .workflows import (
    ConnectorDispatchWorkflow,
    MatterBatchWorkflow,
    MatterTaskWorkflow,
)

PACKAGE_NAME = "sklegal-worker"

__all__ = [
    "BASE_NON_RETRYABLE_ERROR_TYPES",
    "INTERACTIVE_CONTEXT_TOKEN_LIMIT",
    "LONG_CONTEXT_MAX_CONCURRENT",
    "PACKAGE_NAME",
    "RETRY_SPECS",
    "TASK_QUEUE_NAMES",
    "TERMINAL_PHASES",
    "WORKER_DATA_CONVERTER",
    "AdmissionRejectedError",
    "AdmissionTicket",
    "ApprovalGate",
    "ApprovalRejectedError",
    "ApprovalRequirement",
    "ApprovalSignal",
    "ConnectorDispatchWorkflow",
    "DispatchLedger",
    "DispatchReceipt",
    "DispatchRequest",
    "EventKind",
    "FileDispatchLedger",
    "InMemoryStaleAlertSink",
    "LongContextAdmission",
    "MatterBatchWorkflow",
    "MatterTaskWorkflow",
    "ModelUnavailableError",
    "PolicyDeniedError",
    "QueueKind",
    "RetryClass",
    "RetrySpec",
    "RunConfig",
    "RunEvent",
    "RunIdentity",
    "RunPhase",
    "Sha256Digest",
    "SimulatedDispatchLedger",
    "SimulatedStepDriver",
    "Slug",
    "StaleAlertSink",
    "StaleRunAlert",
    "StaticApprovalGate",
    "StepActivityInput",
    "StepDriver",
    "StepOutcome",
    "StepRecord",
    "TaskWorkflowInput",
    "TaskWorkflowResult",
    "UtcDateTime",
    "WorkerActivities",
    "WorkerSpec",
    "WorkflowError",
    "WorkflowInvariantError",
    "WorkflowPayload",
    "WorkflowRunMachine",
    "attempts_exhausted",
    "build_worker",
    "connect_worker_client",
    "is_retryable",
    "retry_policy_for",
    "retry_spec_for",
    "select_queue",
    "task_queue_name",
    "worker_specs",
]
