"""Append-only audit, transactional outbox, and protected telemetry."""

from .adapters import (
    APPEND_AUDIT_EVENT_SQL,
    AuditRepository,
    DurableAuditSink,
    PostgresAuditRepository,
)
from .ledger import (
    AuditUnavailable,
    InMemoryAuditLedger,
    WatermarkConflict,
    recompute_event_sha256,
    verify_event_chain,
)
from .models import (
    AuditAttributes,
    AuditBoundary,
    AuditEventDraft,
    AuditOutcome,
    DurableAuditEvent,
    OutboxDelivery,
    OutboxMessage,
    ProjectionWatermark,
    RunCorrelation,
    TelemetrySpan,
    TelemetryStatus,
)
from .reconciliation import (
    DerivedRecordPin,
    DerivedRecordState,
    DerivedStateStale,
    DerivedStore,
    DerivedStoreKind,
    DerivedStoreUnavailable,
    InMemoryDerivedStore,
    PolicyRevisionOutbox,
    PolicyRevisionReconciler,
    PolicyRevisionView,
    ReconciliationReport,
    ReconciliationUnavailable,
    StoredDerivedRecord,
    StoreReconciliationCounts,
)
from .telemetry import LocalTelemetryBuffer, TraceContextPropagator

PACKAGE_NAME = "sklegal-audit"

__all__ = [
    "APPEND_AUDIT_EVENT_SQL",
    "PACKAGE_NAME",
    "AuditAttributes",
    "AuditBoundary",
    "AuditEventDraft",
    "AuditOutcome",
    "AuditRepository",
    "AuditUnavailable",
    "DerivedRecordPin",
    "DerivedRecordState",
    "DerivedStateStale",
    "DerivedStore",
    "DerivedStoreKind",
    "DerivedStoreUnavailable",
    "DurableAuditEvent",
    "DurableAuditSink",
    "InMemoryAuditLedger",
    "InMemoryDerivedStore",
    "LocalTelemetryBuffer",
    "OutboxDelivery",
    "OutboxMessage",
    "PolicyRevisionOutbox",
    "PolicyRevisionReconciler",
    "PolicyRevisionView",
    "PostgresAuditRepository",
    "ProjectionWatermark",
    "ReconciliationReport",
    "ReconciliationUnavailable",
    "RunCorrelation",
    "StoreReconciliationCounts",
    "StoredDerivedRecord",
    "TelemetrySpan",
    "TelemetryStatus",
    "TraceContextPropagator",
    "WatermarkConflict",
    "recompute_event_sha256",
    "verify_event_chain",
]
